# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false

# Kotlin
kotlin.code.style=official

# Enable Kotlin incremental compilation
kotlin.incremental=true

# Fix for JDK image transformation issues
#org.gradle.java.installations.auto-detect=false
#org.gradle.java.installations.auto-download=false
