package com.amazonaws.regions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class RegionDefaults {
    RegionDefaults() {
    }

    public static List<Region> getRegions() {
        List<Region> ret = new ArrayList();
        Region region = new Region("us-east-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.us-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.us-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.us-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.us-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.us-east-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "firehose", "firehose.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.us-east-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.us-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.us-east-1.amazonaws.com", true, true);
        updateRegion(region, "email", "email.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-sync", "cognito-sync.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-identity", "cognito-identity.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-idp", "cognito-idp.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.us-east-1.amazonaws.com", false, true);
        updateRegion(region, "execute-api", "iot.us-east-1.amazonaws.com", false, true);
        region = new Region("us-west-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.us-west-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.us-west-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.us-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.us-west-1.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.us-west-1.amazonaws.com", false, true);
        region = new Region("us-west-2", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.us-west-2.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.us-west-2.amazonaws.com", false, true);
        updateRegion(region, "firehose", "firehose.us-west-2.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.us-west-2.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.us-west-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.us-west-2.amazonaws.com", true, true);
        updateRegion(region, "email", "email.us-west-2.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.us-west-2.amazonaws.com", false, true);
        updateRegion(region, "execute-api", "iot.us-west-2.amazonaws.com", false, true);
        region = new Region("ap-south-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-ap-south-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-south-1.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        region = new Region("ap-northeast-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-northeast-1.amazonaws.com", true, true);
        updateRegion(region, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region, "execute-api", "iot.ap-northeast-1.amazonaws.com", false, true);
        region = new Region("ap-northeast-2", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-northeast-2.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        region = new Region("ap-southeast-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-southeast-1.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        region = new Region("ap-southeast-2", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-southeast-2.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        region = new Region("sa-east-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.sa-east-1.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.sa-east-1.amazonaws.com", false, true);
        region = new Region("eu-west-1", "");
        ret.add(region);
        updateRegion(region, "s3", "s3-eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SimpleDB, "sdb.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "firehose", "firehose.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.eu-west-1.amazonaws.com", true, true);
        updateRegion(region, "email", "email.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-sync", "cognito-sync.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "cognito-identity", "cognito-identity.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.eu-west-1.amazonaws.com", false, true);
        updateRegion(region, "execute-api", "iot.eu-west-1.amazonaws.com", false, true);
        region = new Region("eu-central-1", "");
        ret.add(region);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, "s3", "s3.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.eu-central-1.amazonaws.com", true, true);
        updateRegion(region, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        region = new Region("cn-north-1", "amazonaws.com.cn");
        ret.add(region);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, "s3", "s3.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.cn-north-1.amazonaws.com.cn", true, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.cn-north-1.amazonaws.com.cn", true, true);
        region = new Region("us-gov-west-1", "");
        ret.add(region);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.us-gov-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.us-gov-west-1.amazonaws.com", true, true);
        updateRegion(region, "s3", "s3-us-gov-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.STS, "sts.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.us-gov-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.us-gov-west-1.amazonaws.com", true, true);
        updateRegion(region, ServiceAbbreviations.CloudWatch, "monitoring.us-gov-west-1.amazonaws.com", false, true);
        return ret;
    }

    private static void updateRegion(Region region, String service, String host, boolean http, boolean https) {
        Map<String, String> serviceEndpoints = region.getServiceEndpoints();
        Map<String, Boolean> httpSupport = region.getHttpSupport();
        Map<String, Boolean> httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(service, host);
        httpSupport.put(service, Boolean.valueOf(http));
        httpsSupport.put(service, Boolean.valueOf(https));
    }
}
